### ISSUE TITLE
Remove DRC from pr repo

### ISSUE THREAD

**Issue by atorkmabrains** [mabrains/globalfoundries-pdk-libs-gf180mcu_fd_pr#122]
DRC has been moved to PV repo. We need to remove it from pr repo and add appropriate documentation for that.

**Comment by atorkmabrains** [comment]
@FaragElsayed2 as we have discussed, please remove the submodule from here.

**Comment by FaragElsayed2** [comment]
@atorkmabrains Done

**Comment by atorkmabrains** [comment]
Thanks @FaragElsayed2
