### ISSUE TITLE
macro DRC problems 

### ISSUE THREAD

**Issue by juan2175606** [mabrains/globalfoundries-pdk-libs-gf180mcu_fd_pr#153]
download the latest version from this repository today, and copy these files, however, the macros have a lot of DRC errors. (67 error DRC)

![Screenshot from 2023-07-24 01-07-17](https://github.com/mabrains/globalfoundries-pdk-libs-gf180mcu_fd_pr/assets/82684670/c7b99ecb-1926-4669-bd00-a62d6e7ed236)
![Screenshot from 2023-07-24 01-06-52](https://github.com/mabrains/globalfoundries-pdk-libs-gf180mcu_fd_pr/assets/82684670/459980d5-3dc3-43b4-9e35-58555648f7e6)

**Comment by FaragElsayed2** [comment]
@juan2175606 Fixed in latest version

**Comment by juan2175606** [comment]
I downloaded the latest version from the repository and the problems continue

![b](https://github.com/mabrains/globalfoundries-pdk-libs-gf180mcu_fd_pr/assets/82684670/61f7c0c0-7fd7-41ac-89db-3a8987a1fdb9)
![a](https://github.com/mabrains/globalfoundries-pdk-libs-gf180mcu_fd_pr/assets/82684670/15062040-3ac1-4f35-ad61-40eed195167c)

**Comment by FaragElsayed2** [comment]
@juan2175606 Please send details of Pcell you have used to check
